version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing Python dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running unit tests...
      - pytest tests/

  build:
    commands:
      - echo Starting model training or app packaging...
      - python train_model.py

  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p build
      - cp -r app/ build/  # Copy application files for packaging
      - cp model.pkl build/  # If you create a trained model

artifacts:
  files:
    - build/**/*
    - requirements.txt
    - buildspec.yml
  discard-paths: no
