name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Example: pytest or unittest
        # Ensure you have tests in a `tests/` directory
        pytest

#   docker-build:
#     needs: build-and-test
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Build FastAPI image
#       run: docker build -t loan-fastapi -f Dockerfile .

#     - name: Build Streamlit image
#       run: docker build -t loan-streamlit -f Streamlit.Dockerfile .

    # Uncomment and configure below to push to Docker Hub or other registry
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push images
    #   run: |
    #     docker tag loan-fastapi your_dockerhub/loan-fastapi
    #     docker push your_dockerhub/loan-fastapi
    #     docker tag loan-streamlit your_dockerhub/loan-streamlit
    #     docker push your_dockerhub/loan-streamlit

#   deploy:
#     needs: docker-build
#     if: github.ref == 'refs/heads/main'
#     runs-on: ubuntu-latest

    
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Deploy with Docker Compose
    #   run: |
    #     docker-compose up -d --build
